fix: Goreleaser fixes
observIQ/stanza pull request #591
Opened 2022-02-28 20:34 UTC by BinaryFissionGames

## Description of Changes
* Fix goreleaser attaching binaries to the release with incorrect naming convention
* Fix goreleaser not attaching scripts + plugins to release
  * This resulted in removing the post-build script. 
* Change script to suffix windows binary with ".exe" for future releases (releases after 1.6.0)
  * This is kinda messy and I'd prefer to just keep the name of the binary as it was (no .exe), but unfortunately goreleaser  hard-codes the .exe suffix for windows binaries.
  * I have tested this script to ensure it generates the correct download URL for previous and future releases when specifying the `--version` flag.

## **Please check that the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CI passes

2022-03-01 13:09 UTC, cpheps submitted a review, later dismissed

2022-03-02 18:11 UTC, jsirianni requested changes
I added this to the post script
```
tar -xf ./artifacts/stanza-plugins.tar.gz -C ./artifacts
```
Which will be removed here. [My package PR](https://github.com/observIQ/stanza/pull/592) depends on `artifacts/plugins` being present. Can we add that here?

2022-03-02 18:18 UTC, BinaryFissionGames commented
Once the package PR is merged, I'll rebase and take that into account.

2022-03-02 18:18 UTC, jsirianni commented
> Once the package PR is merged, I'll rebase and take that into account.

Merged :+1:

2022-03-02 18:58 UTC, cpheps approved these changes

2022-03-02 18:59 UTC, merged